// Verified redirect mapping (STEP 7D/7F) -- generated by
// `python -m sales_ai.cli redirect-map-export`, never hand-edited.
// Regenerate and replace this whole file when published content
// changes; do not add/remove entries by hand.
export default {
  "10": {
    "18": "https://hb.afl.rakuten.co.jp/hgc/g00tyj6o.bhvod18b.g00tyj6o.bhvoe3db/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Flifeideas%2Fwjpppethotm01%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Flifeideas%2Fi%2F10023538%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821"
  },
  "11": {
    "20": "https://hb.afl.rakuten.co.jp/hgc/g00r69mo.bhvod4dd.g00r69mo.bhvoefb5/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fpet-and-pet%2Fbowl-keat-l%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fpet-and-pet%2Fi%2F10000265%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821"
  },
  "13": {
    "24": "https://hb.afl.rakuten.co.jp/hgc/g00u3cco.bhvod2f1.g00u3cco.bhvoea38/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fiegeek%2Fyl-826%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fiegeek%2Fi%2F10000000%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821"
  },
  "14": {
    "26": "https://hb.afl.rakuten.co.jp/hgc/g00t5gno.bhvod288.g00t5gno.bhvoefef/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Ffreebird%2Ftr25se014%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Ffreebird%2Fi%2F10000478%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821"
  },
  "15": {
    "28": "https://hb.afl.rakuten.co.jp/hgc/g00u3nao.bhvod4e3.g00u3nao.bhvoe423/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fgreeneir%2F913-petmat-xl%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fgreeneir%2Fi%2F10000037%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821"
  },
  "16": {
    "30": "https://hb.afl.rakuten.co.jp/hgc/g00pyeeo.bhvod20b.g00pyeeo.bhvoe311/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fashu%2Ft-090765-2%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fashu%2Fi%2F10004216%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821"
  },
  "17": {
    "32": "https://hb.afl.rakuten.co.jp/hgc/g00siyco.bhvod04a.g00siyco.bhvoec9f/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fesuon-angel%2Fz81013000%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fesuon-angel%2Fi%2F10000360%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821"
  },
  "18": {
    "34": "https://hb.afl.rakuten.co.jp/hgc/g00s5lzo.bhvod728.g00s5lzo.bhvoe8a4/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fryouhin-monogatari%2F10000032%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fryouhin-monogatari%2Fi%2F10000051%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821"
  },
  "19": {
    "36": "https://hb.afl.rakuten.co.jp/hgc/g00pjh9o.bhvod56a.g00pjh9o.bhvoeca0/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Funidy%2F202042%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Funidy%2Fi%2F11168880%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821"
  },
  "24": {
    "46": "https://hb.afl.rakuten.co.jp/hgc/g00tfbho.bhvod97f.g00tfbho.bhvoe4aa/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fnext-online%2Fpet-trimerb%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fnext-online%2Fi%2F10000162%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821"
  },
  "25": {
    "48": "https://hb.afl.rakuten.co.jp/hgc/g00tfbho.bhvod97f.g00tfbho.bhvoe4aa/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fnext-online%2F10000268%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fnext-online%2Fi%2F10000248%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821"
  },
  "26": {
    "50": "https://hb.afl.rakuten.co.jp/hgc/g00u7bdo.bhvod289.g00u7bdo.bhvoee2c/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fnswshop%2Fcwse-003%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fnswshop%2Fi%2F10000125%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821"
  },
  "27": {
    "52": "https://hb.afl.rakuten.co.jp/hgc/g00um37o.bhvod27f.g00um37o.bhvoe480/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fetlifeshop001%2Fsocks%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fetlifeshop001%2Fi%2F10000002%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821"
  },
  "28": {
    "55": "https://hb.afl.rakuten.co.jp/hgc/g00ppglo.bhvod76d.g00ppglo.bhvoeeff/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Ftansu%2F84100004%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Ftansu%2Fi%2F10056830%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821",
    "56": "https://hb.afl.rakuten.co.jp/hgc/g00rv3wo.bhvodc27.g00rv3wo.bhvoece3/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fauc-iyashi%2Fcoco-0010s%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fauc-iyashi%2Fi%2F10000159%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821"
  },
  "29": {
    "57": "https://hb.afl.rakuten.co.jp/hgc/g00qfyeo.bhvodd93.g00qfyeo.bhvoe35d/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fauc-nikkashop%2Fnk-f25%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fauc-nikkashop%2Fi%2F10007282%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821",
    "58": "https://hb.afl.rakuten.co.jp/hgc/g00q6sro.bhvodf3c.g00q6sro.bhvoebd3/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Faimu%2F4903588224584%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Faimu%2Fi%2F10021210%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821",
    "59": "https://hb.afl.rakuten.co.jp/hgc/g00uih7o.bhvod29a.g00uih7o.bhvoec15/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fpalpia%2Fpf-tw-007%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fpalpia%2Fi%2F10000056%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821"
  },
  "30": {
    "60": "https://hb.afl.rakuten.co.jp/hgc/g00qcuoo.bhvod35e.g00qcuoo.bhvoe52b/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fyamakishi%2F35903512%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fyamakishi%2Fi%2F10111607%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821",
    "61": "https://hb.afl.rakuten.co.jp/hgc/g00tfbho.bhvod97f.g00tfbho.bhvoe4aa/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fnext-online%2F10000184%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fnext-online%2Fi%2F10000185%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821",
    "62": "https://hb.afl.rakuten.co.jp/hgc/g00r13ko.bhvodc41.g00r13ko.bhvoe8e1/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fauc-roadster%2F10007255%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fauc-roadster%2Fi%2F10007255%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821"
  },
  "31": {
    "63": "https://hb.afl.rakuten.co.jp/hgc/g00urswo.bhvod368.g00urswo.bhvoedc4/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fecshopfind1%2F01260710%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fecshopfind1%2Fi%2F10001187%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821",
    "64": "https://hb.afl.rakuten.co.jp/hgc/g00tkyoo.bhvod0d7.g00tkyoo.bhvoe2fd/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Ftoolshopvulcan%2F10001760%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Ftoolshopvulcan%2Fi%2F10001760%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821",
    "65": "https://hb.afl.rakuten.co.jp/hgc/g00ue8go.bhvod84a.g00ue8go.bhvoee0a/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fnagapo%2Fpet-006%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fnagapo%2Fi%2F10000100%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821"
  },
  "32": {
    "66": "https://hb.afl.rakuten.co.jp/hgc/g00q3b1o.bhvod40f.g00q3b1o.bhvoeb1c/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fpetnext%2Fq1600041-a%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fpetnext%2Fi%2F10002864%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821",
    "67": "https://hb.afl.rakuten.co.jp/hgc/g00rtv0o.bhvod884.g00rtv0o.bhvoe04e/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Foganic%2F100000777-045%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Foganic%2Fi%2F10000313%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821",
    "68": "https://hb.afl.rakuten.co.jp/hgc/g00uokoo.bhvod858.g00uokoo.bhvoecc2/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fmerrily-shop%2F100336%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fmerrily-shop%2Fi%2F10000996%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821"
  },
  "33": {
    "69": "https://hb.afl.rakuten.co.jp/hgc/g00pr3zo.bhvod411.g00pr3zo.bhvoebea/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fdog-kan%2F113004%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fdog-kan%2Fi%2F10199457%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821",
    "70": "https://hb.afl.rakuten.co.jp/hgc/g00trp7o.bhvod20e.g00trp7o.bhvoe2cc/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Frecshop%2Ft-07dr01-01%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Frecshop%2Fi%2F10001368%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821",
    "71": "https://hb.afl.rakuten.co.jp/hgc/g00t0p4o.bhvod49d.g00t0p4o.bhvoe37b/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fdogcat-shop%2Fcard01%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fdogcat-shop%2Fi%2F10000028%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821"
  },
  "34": {
    "72": "https://hb.afl.rakuten.co.jp/hgc/g00ue2qo.bhvod1a1.g00ue2qo.bhvoecc8/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fdearkm%2Fkm796g%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fdearkm%2Fi%2F10009587%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821",
    "73": "https://hb.afl.rakuten.co.jp/hgc/g00tpxzo.bhvod0ff.g00tpxzo.bhvoefab/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fbubblee%2Fpetwfh018%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fbubblee%2Fi%2F10007446%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821",
    "74": "https://hb.afl.rakuten.co.jp/hgc/g00uirho.bhvod6ef.g00uirho.bhvoef6c/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fpetforest%2Fpf-4976555858006%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fpetforest%2Fi%2F10019687%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821"
  },
  "35": {
    "75": "https://hb.afl.rakuten.co.jp/hgc/g00sre8o.bhvod21c.g00sre8o.bhvoe4d7/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Ffukuryusen%2F10000003%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Ffukuryusen%2Fi%2F10000004%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821",
    "76": "https://hb.afl.rakuten.co.jp/hgc/g00qewfo.bhvoda5e.g00qewfo.bhvoec77/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fg-sarai%2F10000074%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fg-sarai%2Fi%2F10000074%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821",
    "77": "https://hb.afl.rakuten.co.jp/hgc/g00ugyno.bhvod44e.g00ugyno.bhvoe651/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Frakutensokuhaimart%2F4987072096789%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Frakutensokuhaimart%2Fi%2F10027941%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821"
  },
  "36": {
    "78": "https://hb.afl.rakuten.co.jp/hgc/g00qy5uo.bhvod569.g00qy5uo.bhvoe92d/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fdhcshop%2F8000002496%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fdhcshop%2Fi%2F10002665%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821",
    "79": "https://hb.afl.rakuten.co.jp/hgc/g00sbglo.bhvod020.g00sbglo.bhvoe835/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fstarmall%2F4560191494928%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fstarmall%2Fi%2F10064784%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821",
    "80": "https://hb.afl.rakuten.co.jp/hgc/g00rj4zo.bhvod01e.g00rj4zo.bhvoe9ba/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fmineters-dogfood%2Ftrial-set-009%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fmineters-dogfood%2Fi%2F10000764%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821"
  },
  "37": {
    "81": "https://hb.afl.rakuten.co.jp/hgc/g00rtv0o.bhvod884.g00rtv0o.bhvoe04e/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Foganic%2F100000777-777%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Foganic%2Fi%2F10000135%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821",
    "82": "https://hb.afl.rakuten.co.jp/hgc/g00r6h3o.bhvoda93.g00r6h3o.bhvoed44/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fd-fit%2Fppp518%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fd-fit%2Fi%2F10011909%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821",
    "83": "https://hb.afl.rakuten.co.jp/hgc/g00rtv0o.bhvod884.g00rtv0o.bhvoe04e/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Foganic%2F100000777-778%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Foganic%2Fi%2F10000137%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821"
  },
  "38": {
    "84": "https://hb.afl.rakuten.co.jp/hgc/g00qyjuo.bhvoddec.g00qyjuo.bhvoe293/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fsnowdrop%2Fw024%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fsnowdrop%2Fi%2F10005518%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821",
    "85": "https://hb.afl.rakuten.co.jp/hgc/g00u5hno.bhvod9f9.g00u5hno.bhvoe2ff/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fkawausokko%2Fzzy-cwyf-001%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fkawausokko%2Fi%2F10000465%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821",
    "86": "https://hb.afl.rakuten.co.jp/hgc/g00uuzyo.bhvod5ee.g00uuzyo.bhvoec65/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Frooty%2Frot6151%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Frooty%2Fi%2F10000127%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821"
  },
  "39": {
    "87": "https://hb.afl.rakuten.co.jp/hgc/g00szdto.bhvod264.g00szdto.bhvoe593/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fdogfood-koubou%2F300001%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fdogfood-koubou%2Fi%2F10000239%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821",
    "88": "https://hb.afl.rakuten.co.jp/hgc/g00rj4zo.bhvod01e.g00rj4zo.bhvoe9ba/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fmineters-dogfood%2Fpet-nyuusankin%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fmineters-dogfood%2Fi%2F10000914%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821",
    "89": "https://hb.afl.rakuten.co.jp/hgc/g00qct7o.bhvod4bc.g00qct7o.bhvoee3c/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fedenki%2Fed3028195%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fedenki%2Fi%2F18595780%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821"
  },
  "40": {
    "90": "https://hb.afl.rakuten.co.jp/hgc/g00upe8o.bhvod7b0.g00upe8o.bhvoe712/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fkurashi-picks%2Fb0020%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fkurashi-picks%2Fi%2F10000021%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821",
    "91": "https://hb.afl.rakuten.co.jp/hgc/g00upsao.bhvodaff.g00upsao.bhvoe667/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fnextdaily%2Fdjj26821%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fnextdaily%2Fi%2F10001029%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821",
    "92": "https://hb.afl.rakuten.co.jp/hgc/g00t1v2o.bhvoded6.g00t1v2o.bhvoe178/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Femoor-nedogko%2Fkt-carebag%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Femoor-nedogko%2Fi%2F10000466%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821"
  },
  "6": {
    "10": "https://hb.afl.rakuten.co.jp/hgc/g00t1v2o.bhvoded6.g00t1v2o.bhvoe178/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Femoor-nedogko%2Fcy-kaigodogbed%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Femoor-nedogko%2Fi%2F10000366%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821",
    "53": "https://hb.afl.rakuten.co.jp/hgc/g00pwhco.bhvod376.g00pwhco.bhvoec07/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fidog%2F16299%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fidog%2Fi%2F10018241%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821",
    "54": "https://hb.afl.rakuten.co.jp/hgc/g00pyeeo.bhvod20b.g00pyeeo.bhvoe311/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fashu%2Fcm-000im%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fashu%2Fi%2F10007208%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821"
  },
  "7": {
    "12": "https://hb.afl.rakuten.co.jp/hgc/g00ukrao.bhvod94f.g00ukrao.bhvoe1e9/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fonlineshop-yk%2Fcompass1719386324%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fonlineshop-yk%2Fi%2F10000033%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821"
  }
};
