// Verified redirect mapping (STEP 7D/7F) -- generated by
// `python -m sales_ai.cli redirect-map-export`, never hand-edited.
// Regenerate and replace this whole file when published content
// changes; do not add/remove entries by hand.
export default {
  "10": {
    "18": "https://hb.afl.rakuten.co.jp/hgc/g00tyj6o.bhvod18b.g00tyj6o.bhvoe3db/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Flifeideas%2Fwjpppethotm01%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Flifeideas%2Fi%2F10023538%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821"
  },
  "11": {
    "20": "https://hb.afl.rakuten.co.jp/hgc/g00r69mo.bhvod4dd.g00r69mo.bhvoefb5/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fpet-and-pet%2Fbowl-keat-l%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fpet-and-pet%2Fi%2F10000265%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821"
  },
  "13": {
    "24": "https://hb.afl.rakuten.co.jp/hgc/g00u3cco.bhvod2f1.g00u3cco.bhvoea38/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fiegeek%2Fyl-826%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fiegeek%2Fi%2F10000000%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821"
  },
  "14": {
    "26": "https://hb.afl.rakuten.co.jp/hgc/g00t5gno.bhvod288.g00t5gno.bhvoefef/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Ffreebird%2Ftr25se014%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Ffreebird%2Fi%2F10000478%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821"
  },
  "15": {
    "28": "https://hb.afl.rakuten.co.jp/hgc/g00u3nao.bhvod4e3.g00u3nao.bhvoe423/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fgreeneir%2F913-petmat-xl%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fgreeneir%2Fi%2F10000037%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821"
  },
  "16": {
    "30": "https://hb.afl.rakuten.co.jp/hgc/g00pyeeo.bhvod20b.g00pyeeo.bhvoe311/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fashu%2Ft-090765-2%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fashu%2Fi%2F10004216%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821"
  },
  "6": {
    "10": "https://hb.afl.rakuten.co.jp/hgc/g00t1v2o.bhvoded6.g00t1v2o.bhvoe178/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Femoor-nedogko%2Fcy-kaigodogbed%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Femoor-nedogko%2Fi%2F10000366%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821"
  },
  "7": {
    "12": "https://hb.afl.rakuten.co.jp/hgc/g00ukrao.bhvod94f.g00ukrao.bhvoe1e9/?pc=https%3A%2F%2Fitem.rakuten.co.jp%2Fonlineshop-yk%2Fcompass1719386324%2F&m=http%3A%2F%2Fm.rakuten.co.jp%2Fonlineshop-yk%2Fi%2F10000033%2F&rafcid=wsc_i_is_56671c4a-e7ee-4387-8d8d-d1636facc821"
  }
};
